services:
  workspace:
    build:
      context: ./dockerfiles/workspace
      args:
        - PHP_XDEBUG=$PHP_XDEBUG
    tty: true
    volumes:
      - .:/var/www/
  redis:
    image: redis:7.0.4-alpine3.16
    restart: unless-stopped
    command: redis-server --save 20 1 --loglevel notice --requirepass ${REDIS_PASSWORD}
    expose:
      - 6379
  database:
    image: mysql:8.0.29
    restart: unless-stopped
    volumes:
      - ./dockerfiles/mysql/data:/var/lib/mysql/
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}