services:
  caddy:
    build:
      context: ./dockerfiles/caddy
      args:
        - APP_ENV=$APP_ENV
        - APP_URL=$APP_URL
    restart: unless-stopped
    volumes:
      - .:/var/www/
      - ./dockerfiles/caddy/data/config:/config
      - ./dockerfiles/caddy/data/data:/data
    ports:
      - 80:80
      - 443:443
      - 6001:6001
    env_file: .env
  php:
    build:
      context: ./dockerfiles/php
      args:
        - WITH_XDEBUG=$DEV_XDEBUG
        - APP_ENV=$APP_ENV
    restart: unless-stopped
    volumes:
       - .:/var/www/
    expose:
      - 9000
    env_file: .env
  workspace:
    build: ./dockerfiles/workspace
    tty: true
    ports:
      - 1234:1234
    volumes:
      - .:/var/www/
  redis:
    image: redis:7.0.4-alpine3.16
    restart: unless-stopped
    command: redis-server --save 20 1 --loglevel notice --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
  workers:
    build: ./dockerfiles/workers
    tty: true
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - .:/var/www/
  database:
    image: mysql:8.0.29
    restart: unless-stopped
    volumes:
      - ./dockerfiles/mysql/data:/var/lib/mysql/
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}