services:
  workspace:
    image: performave/convoy-workspace:latest
    tty: true
    volumes:
      - .:/var/www/
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
  redis:
    image: redis:7.0-alpine
    restart: unless-stopped
    command: redis-server --save 20 1 --loglevel notice --requirepass ${REDIS_PASSWORD}
    expose:
      - 6379
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    healthcheck:
      test: redis-cli -a $$REDIS_PASSWORD ping | grep PONG
      interval: 5s
      timeout: 5s
      retries: 20
  database:
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - ./dockerfiles/mysql/data:/var/lib/mysql/
    expose:
      - 3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: mysqladmin ping -u$$MYSQL_USER -p$$MYSQL_PASSWORD
      interval: 5s
      timeout: 5s
      retries: 20
