services:
  nginx:
    build: ./dockerfiles/nginx
    volumes:
      - .:/var/www/html/
    ports:
      - 80:80
      - 443:443
  php:
    build: ./dockerfiles/php
    volumes:
      # - ./dockerfiles/php-fpm/php.ini:/usr/local/etc/php/php.ini
       - .:/var/www/html/
    expose:
      - 9000
  workspace:
    build: ./dockerfiles/workspace
    tty: true
    environment:
      - LARAVEL_SAIL=true
    ports:
      - 3000:3000
      - 5173:5173
    volumes:
      - .:/app/
  redis:
    image: redis:7.0.4-alpine3.16
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
  database:
    image: mysql:8.0.29
    volumes:
      - ./dockerfiles/mysql/data:/var/lib/mysql/
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}