services:
  nginx:
    build: ./dockerfiles/nginx
    restart: unless-stopped
    volumes:
      - .:/var/www/html/
    ports:
      - 80:80
      - 443:443
  php:
    build:
      context: ./dockerfiles/php
      args:
        - WITH_XDEBUG=$DEV_XDEBUG
    restart: unless-stopped
    volumes:
       - .:/var/www/html/
    expose:
      - 9000
    env_file: .env
  workspace:
    build: ./dockerfiles/workspace
    tty: true
    environment:
      - LARAVEL_SAIL=true
    ports:
      - 3000:3000
      - 5173:5173
    volumes:
      - .:/app/
  redis:
    image: redis:7.0.4-alpine3.16
    restart: unless-stopped
    command: redis-server --save 20 1 --loglevel notice --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
  php-worker:
    build: ./dockerfiles/php-worker
    tty: true
    restart: unless-stopped
    working_dir: /var/www/html/
    volumes:
      - .:/var/www/html/
  soketi:
    restart: unless-stopped
    image: 'quay.io/soketi/soketi:1.4-16-alpine'
    ports:
      - '${SOKETI_PORT:-6001}:6001'
      - '${SOKETI_METRICS_SERVER_PORT:-9601}:9601'
    environment:
      - DEBUG='${DEBUG:-1}'
      - PUSHER_APP_ID='${PUSHER_APP_ID}'
      - PUSHER_APP_KEY='${PUSHER_APP_KEY}'
      - PUSHER_APP_SECRET='${PUSHER_APP_SECRET}'
      - PUSHER_HOST='${PUSHER_HOST:-127.0.0.1}'
      - PUSHER_PORT= '${PUSHER_PORT:-6001}'
      - PUSHER_SCHEME='${PUSHER_SCHEME:-http}'
      - METRICS_SERVER_PORT=${METRICS_SERVER_PORT-9601}
      - DEFAULT_APP_ENABLE_CLIENT_MESSAGES=${DEFAULT_APP_ENABLE_CLIENT_MESSAGES-false}
  database:
    image: mysql:8.0.29
    restart: unless-stopped
    volumes:
      - ./dockerfiles/mysql/data:/var/lib/mysql/
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}