name: Tests
on:
  push:
    branches:
      - 'develop'
      - '3.0-develop'
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create environment file
        run: cp .env.ci .env

      - name: Start Docker Containers
        run: docker compose up -d database redis workspace

      - name: Install dependencies
        run: docker compose exec workspace composer install --prefer-dist --no-interaction --no-progress

      - name: Wait for database to initialize
        run: sleep 10

      - name: Run database migrations
        run: docker compose exec workspace php artisan migrate

      - name: Run tests
        run: docker compose exec workspace vendor/bin/pest --bootstrap vendor/autoload.php tests/Feature